# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('vlc-wifi', ['core','network','propagation'])
    module.source = [
        'model/vlc-wifi.cc',
        'helper/vlc-wifi-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('vlc-wifi')
    module_test.source = [
        'test/vlc-wifi-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'vlc-wifi'
    headers.source = [
        'model/vlc-wifi.h',
        'helper/vlc-wifi-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

     bld.ns3_python_bindings()

